name: Guilds
main: com.cornchipss.guilds.GuildsPlugin
version: 1.0
commands:
    guilds:
        description: Gateway to all guilds commands
        usage: /guilds
    guildchat:
        description: Guild Chat
        usage: /guildchat
    gc:
        description: Guild Chat
        usage: /gc